class_name MapNode
extends Resource

## A single node in a region's runtime map graph. Generated by
## RegionPlanner; never authored. position is in viewport coordinates
## of the play scene (the planner picks it). prev_ids enables
## reconvergence checks; next_ids drives the player's available choices.
##
## Uses Resource (not RefCounted) per CLAUDE.md migrability rule:
## "Resource subclasses for records — no duck-typed dicts." Runtime-only
## but we still get inspector/debug visibility for free.

var id: int = -1
var position: Vector2 = Vector2.ZERO
var kind: int = 0
var next_ids: Array[int] = []
var prev_ids: Array[int] = []
