class_name MapNode
extends RefCounted

## A single node in a region's runtime map graph. Generated by
## RegionPlanner; never authored. position is in viewport coordinates
## of the play scene (the planner picks it). prev_ids enables
## reconvergence checks; next_ids drives the player's available choices.

var id: int = -1
var position: Vector2 = Vector2.ZERO
var kind: int = 0
var next_ids: Array[int] = []
var prev_ids: Array[int] = []
