class_name RealmNode
extends Resource

## A single region-slot in the runtime Realm graph. Generated by
## RealmPlanner; never authored. position is in canvas coordinates of
## the realm-map scene (the planner picks it from the fixed layout).
##
## Resource (not RefCounted) per CLAUDE.md migrability rule. Same
## precedent as MapNode.

@export var id: int = -1
@export var column: int = 0
@export var row: int = 0
@export var region_id: StringName = &""
@export var position: Vector2 = Vector2.ZERO
@export var next_ids: Array[int] = []
@export var prev_ids: Array[int] = []
